smtp:
  port: 1025
  sessionTimeout: 60000

submission:
  port: 1587
  sessionTimeout: 60000

pop3:
  port: 1995
  sessionTimeout: 60000

spam:
  enabled: false # You must have a working SpamAssassin and SpamD daemon before enabling this
  spamAssassinUrl: 127.0.0.1
  spamAssassinPort: 783

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mail
    username: root
    password: azerty
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

servers:
  autostart: true # autostart servers on application startup